// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz4liq53ZIJFOGD_c4Brprx8hjNwzQeMc',
    appId: '1:828869896995:web:f1539944487e9478fdfa96',
    messagingSenderId: '828869896995',
    projectId: 'bartender-app-503a2',
    authDomain: 'bartender-app-503a2.firebaseapp.com',
    databaseURL: 'https://bartender-app-503a2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bartender-app-503a2.firebasestorage.app',
    measurementId: 'G-HN74SG7WC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_2IjIzl1nTWEhW5PQnin72f4tgUS6xpA',
    appId: '1:828869896995:android:5b44fa624698c436fdfa96',
    messagingSenderId: '828869896995',
    projectId: 'bartender-app-503a2',
    databaseURL: 'https://bartender-app-503a2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bartender-app-503a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTVEg6GEG9_KCQjK2xUuG00Rh6MlL_hzI',
    appId: '1:828869896995:ios:1b2c46753ecf4c49fdfa96',
    messagingSenderId: '828869896995',
    projectId: 'bartender-app-503a2',
    databaseURL: 'https://bartender-app-503a2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bartender-app-503a2.firebasestorage.app',
    iosBundleId: 'com.example.doan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTVEg6GEG9_KCQjK2xUuG00Rh6MlL_hzI',
    appId: '1:828869896995:ios:1b2c46753ecf4c49fdfa96',
    messagingSenderId: '828869896995',
    projectId: 'bartender-app-503a2',
    databaseURL: 'https://bartender-app-503a2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bartender-app-503a2.firebasestorage.app',
    iosBundleId: 'com.example.doan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz4liq53ZIJFOGD_c4Brprx8hjNwzQeMc',
    appId: '1:828869896995:web:d6aa18f5fd40f417fdfa96',
    messagingSenderId: '828869896995',
    projectId: 'bartender-app-503a2',
    authDomain: 'bartender-app-503a2.firebaseapp.com',
    databaseURL: 'https://bartender-app-503a2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bartender-app-503a2.firebasestorage.app',
    measurementId: 'G-LKPLJCDJT4',
  );

}